Models/ErrorViewModel.cs
using System;

namespace Internet_Tech_1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Models
{
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IsService { get; set; }
    }
}

Models/Reviews.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Models
{
    public class Reviews
    {
        public int ID { get; set; }
        public string User { get; set; }
        public string Text { get; set; }
    }
}

Models/Vacancies.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Models
{
    public class Vacancies
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Salary { get; set; }
    }
}

Controllers/CompanyController.cs
using Internet_Tech_1.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class CompanyController : Controller
    {
        private ApplicationContext db;

        public CompanyController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Company()
        {
            return View();
        }
    }
}

Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class FeedbackController : Controller
    {
        public IActionResult Feedback()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Internet_Tech_1.Context;
using Internet_Tech_1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationContext db;

        public HomeController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View(db.Product.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductsController.cs
using Internet_Tech_1.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationContext db;

        public ProductsController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Products()
        {
            return View(db.Product.ToList());
        }
    }
}

Controllers/VacanciesController.cs
using Internet_Tech_1.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class VacanciesController : Controller
    {
        private ApplicationContext db;

        public VacanciesController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Vacancies()
        {
            return View(db.Vacancies.ToList());
        }
    }
}

Controllers/СontactsController.cs
using Internet_Tech_1.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Internet_Tech_1.Controllers
{
    public class СontactsController : Controller
    {
        private ApplicationContext db;

        public СontactsController(ApplicationContext context)
        {
            db = context;
        }
        public IActionResult Сontacts()
        {
            return View();
        }
    }
}

Views/Company/Company.cshtml
@{
    ViewData["Title"] = "About company";
}

<body>
    <div>
        <h1>О компании</h1>
        <p>Текст о компании</p>
    </div>

    <div>
        <h1>Наши принципы</h1>
        <p>Тут принципы</p>
    </div>

</body>

Views/Feedback/Feedback.cshtml
@{
    ViewData["Title"] = "Feedback";
}

<body>
    <h2>Обратная связь</h2>
    <form>
        <div class="form-group">
            <label for="exampleInput">ФИО</label>
            <input class="form-control" type="text" placeholder="Введите ваше ФИО">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="E-mail">
            <small id="emailHelp" class="form-text text-muted">Мы никогда никому не передадим вашу электронную почту.</small>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Коментарий</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Напишите мне письмо</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Позвоните мне</label>
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>

</body>

Views/Home/Index.cshtml
@model IEnumerable<Internet_Tech_1.Models.Product>
@{
    ViewData["Title"] = "Home Page";
}

<body>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active h-auto">
                <img class="d-block w-auto" src="https://torggrad.ru/glyphicons/png/o_kompanii.jpg" height="400" alt="First slide">
            </div>
            <div class="carousel-item h-auto">
                <img class="d-block w-auto" src="https://cleverstaff.net/blog/wp-content/uploads/2019/10/korporativnyye-tsennosti-eto.jpg" height="400" alt="Second slide">
            </div>
            <div class="carousel-item h-auto">
                <img class="d-block w-auto" src="https://melsis.ru/images/services/proekti/about_img.jpg" height="400" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div>
        <h2>О компании</h2>
        <p>Какой то текст</p>
    </div>

    <h2>Наши услуги</h2>
    <div class="card-deck">
        @foreach (Product item in Model)
        {
            @if (item.IsService == 1)
            {
                <div class="card border-dark mb-5" style="max-width: 20rem;">
                    <div class="card-header">
                        <h5 class="card-title">@item.Name</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">@item.Description</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary" asp-area="" asp-controller="Feedback" asp-action="Feedback">Обратная связь</a>
                    </div>
                </div>
            }
        }
    </div>

    <div>
        <h2>Отзывы</h2>
        <p>Тут отзывы</p>
    </div>

</body>

Views/Products/Products.cshtml
@model IEnumerable<Internet_Tech_1.Models.Product>
@{
    ViewData["Title"] = "Products";
}

<body>
    <h2>Наши товары и услуги</h2>
    <div class="card-deck">
        @foreach (Product item in Model)
        {
            <div class="card border-dark mb-5" style="max-width: 20rem;">
                <div class="card-header">
                    <h5 class="card-title">@item.Name</h5>
                </div>
                <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBzF5CnAuTPmKhYmYLNW5XbY7KOhvQcUAYHHXgbNri78vz_okot34TGz5bUQyULpKxmKc&usqp=CAU" width="300" height="200" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">@item.Description</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" asp-area="" asp-controller="Feedback" asp-action="Feedback">Обратная связь</a>
                </div>
            </div>
        }
    </div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Internet_Tech_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <nav class="navbar navbar-light">
                    <img src="https://st4.depositphotos.com/20834934/28355/i/600/depositphotos_283555970-stock-photo-watercolor-cake.jpg" width="70" height="70" class="d-inline-block align-top" alt="">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        Тортикус
                    </a>

                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Меню</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Company" asp-action="Company">О компании</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Products" asp-action="Products">Продукты</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Vacancies" asp-action="Vacancies">Вакансии</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Сontacts" asp-action="Сontacts">Контакты</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Feedback" asp-action="Feedback">Обратная связь</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>

            <span class="navbar-text">
                E-mail: tortikys@@mail.ru
                <br>
                Телефон: 8-800-355-35-35
            </span>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Vacancies/Vacancies.cshtml
@model IEnumerable<Internet_Tech_1.Models.Vacancies>
@{
    ViewData["Title"] = "Vacancies";
}

<body>
    <h2>Наши вакансии</h2>
    <div class="card-deck">
        @foreach (Vacancies item in Model)
        {
            <div class="card border-dark mb-5" style="max-width: 20rem;">
                <div class="card-header">
                    <h5 class="card-title">@item.Name</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">@item.Description</p>
                </div>
                <div class="card-footer">
                    <p>Зарплата: @item.Salary</p>
                    <a class="btn btn-primary" asp-area="" asp-controller="Feedback" asp-action="Feedback">Обратная связь</a>
                </div>
            </div>
        }
    </div>

    <div>
        <h2>Контактные данные</h2>
        <p>Наш E-mail: tortikys@@mail.ru </p>
        <p>Наш телефон: 8-800-355-35-35</p>
        <p>Наш адрес:</p>
    </div>

</body>

Views/Сontacts/Сontacts.cshtml
@{
    ViewData["Title"] = "Сontacts";
}

<body>
    <div>
        <h2>Контактные данные</h2>
        <p>Наш E-mail: tortikys@@mail.ru </p>
        <p>Наш телефон: 8-800-355-35-35</p>
        <p>Наш адрес:</p>
    </div>

    <div>
        <h2>Карта проезда</h2>
        <img src="https://lh3.googleusercontent.com/proxy/U-1SQicMrSx4YwBoRKxOsp46JzLdzr_V4JWgYLbfpPh_pcGYQg4HuXVPFnYcRV6QqPoP1QyVFi2F8a0wZMQknEAEQnHnw00jxvRCV1MrvR12Yv854Q" class="img-fluid" alt="Responsive image">
        <p>Описание как проехать</p>
    </div>

</body>